site/components/Footer.js
This feature will make it easier for users to reach out with questions, feedback, or issues, which can improve the overall user experience. It could be linked to an email form or a page with contact information for the project’s maintainers.
=> # ### Feature Request:  I would like to propose adding a "Contact Us" tab to the main navigation bar to improve user interaction and support.

README.md
Hello there @subhadipbhowmik , 
Revamped README.md with:-
- installation instructions and 
- application's information
- sections
- badges and logo
=> Updated README.md  #19

site/components/Process.js
FIX #16  corrected the UI for the component Process.js and adjusted the Alignment for the card
=> corrected the UI Fault

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
**Description**
This PR adds issue and pull request (PR) templates to the repository. These templates are designed to streamline the process for reporting bugs, requesting features, and submitting PRs by providing a consistent structure for contributors to follow.
- **Issue Templates:** 
- Bug report template
- Feature request template
- **Pull Request Template:** 
- Standardized format for PRs to ensure all necessary information is included and follows project guidelines.
**Related Issue**
Closes #28 
**Checklist**
=> Added Issue and pr template

site/components/DetailsCard.js
hey @subhadipbhowmik , 
> [solved issue #7 ]
This PR makes two changes to the DetailsCard component:
When users hover over the cards, they will see a **smooth shadow effect** with **color of shadow same as the card** but little translucent. This makes the cards look more dynamic and visually appealing.
The cursor style has been changed to **cursor-default for all cards**, indicating that they are not clickable. This helps users understand that they can’t interact with the cards.
These changes **improve the look and feel of the cards** and make it clear to users how they can interact with them.
here's a preview
https://github.com/user-attachments/assets/5e45956b-4265-4557-b87f-731b843445bc
Looking forward to get this PR merged as it doesn't alter any other code and clean to be merged ! …
=> Add Hover Shadow Animation and Change Cursor Style on Details Cards 

Learning.md, package-lock.json, site/components/Navbar.js, site/pages/contact.js, site/styles/contact.module.css
Hello PA @subhadipbhowmik ,
I created a contact Us page frontend for the project . Could you kindly review and approve if its alright.
=> @17 Created a contact us page frontend

site/components/Footer.js
=> Updated footer

site/components/DetailsCard.js
=> Change in UI of Features

site/components/Navbar.js
I have updated the buttons in your site and they are looking great with the hover effect ,i have also changed the text color from boring to a color which fit with your website template
Fixes # 38
=> Update and redesign page buttons

site/components/Footer.js, site/components/Process.js
#9 
I improved UI by adding shadow for cards and hover effect for buttons
Fixes UI #9 
- [1] Added shadow effect to the cards in the 'How to Join BioTree' section.
- [ 2]Implemented a hover effect on the buttons.
=> Enhanced Card Shadows and Button Hover Effects

donation/button.html, donation/main.html
My Issue Number #63
Created A Donation page for donation , and a button for it ; it is created for general charity for required well being
- [✔️ ] New feature (non-breaking change which adds functionality)
Bearer , I have created the page for donation and it's button , please establish  it to the main HTML file so that it can be accuired into the main web page
- [✔️ ] I have performed a self-review of my own code
- [✔️ ] I have commented on my code, particularly in hard-to-understand areas
- [ ✔️] I have added tests that prove my fix is effective or that my feature works
- [✔️ ] New and existing unit tests pass locally with my changes
- [✔️ ] Any dependent changes have been merged and published in downstream modules
Screenshots
Added codes
=> Created A Donation Page 

site/pages/apply.js
Fix for Hover Border on Input Tab - Issue #108
Issue:
When users hovered over the input tab, an unwanted border would appear, negatively affecting the user experience by creating a distracting visual effect.
Fix:
This PR addresses the issue by:
Removing the hover border effect on the input tab, ensuring a smoother and more consistent user experience.
Testing Done:
Manually tested the input tab across different browsers and screen sizes to ensure that the border no longer appears on hover.
Verified that all input fields still retain their intended focus and hover behaviors without the border issue.
=> input-border-fix

site/pages/apply.js, site/styles/apply.module.css, site/styles/globals.css
=> Fixed the focus border and add cursor pointer in labels

site/components/Navbar.js
I assigned with moving login nav element to right end to improve ui and ux
Fixes #99 
- [x
] Any dependent changes have been merged and published in downstream modules
=> FIX : nav bar -> moved login element to right end

CONTRIBUTING.md, README.md
https://github.com/user-attachments/assets/7cb92ca4-a9b5-4d54-9be6-60035f8cd5ef
- Fixes - Issue #105
=> Modified README.md file and Contributing.md file.

site/pages/contact.js
The responsiveness of the content page is wrong and need to be fixed so I fixed the bug.
Fixes #130
=> Responsive Issue of Content page Fixed

server/auth.js, server/index.js, site/components/Navbar.js, site/pages/apply.js, site/pages/login.js
Add Google Sign-In feature in login page for easy login to users instead of remembering their passwords
Fixes #139 
https://github.com/user-attachments/assets/2050ac26-50c2-4895-8c4c-98fc4b802c62
- [X ] New feature (non-breaking change which adds functionality)
- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented on my code, particularly in hard-to-understand areas
- [ X] New and existing unit tests pass locally with my changes
=> Add Google Sign-In feature

server/auth.js, server/index.js, site/components/Footer.js, site/components/Navbar.js, site/pages/apply.js, site/pages/login.js
The newsletter section in the website is required for the users to be updated about the latest trends in the website and get notified by the website in their emails.
Fixes #142 
https://github.com/user-attachments/assets/13ea5f6b-42fe-4acc-920d-86d393e087c2
- [X ] New feature (non-breaking change which adds functionality)
- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented on my code, particularly in hard-to-understand areas
- [ X] New and existing unit tests pass locally with my changes
=> Newsletter Submission Form

site/components/Footer.js
=> Revert "Newsletter Submission Form"

site/pages/contact.js
=> contactpage

site/pages/_app.js
added the scroll to top button
Fixes #331 
https://github.com/user-attachments/assets/0ee2be8a-aa93-4b51-992a-73c9e52b2efe
- [ X] New feature (non-breaking change which adds functionality)
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented on my code, particularly in hard-to-understand areas
- [ X] New and existing unit tests pass locally with my changes
=> Added top to scroll button

site/styles/globals.css
made the top navigation bar fixed
=> making top navbar fixed

site/pages/contact.js
Make Contact page responsive.
1. Make Contact page responsive .
2. Add some hover effect in button.
3.  Add some text-colour .
4. Adjust font-size .
5. Add some margin.
=> Make Contact page responsive

site/components/Navbar.js, site/pages/contributor.js
Added the Contributors Page and linked it in the navbar also.
if you have any issue with the PR just mention me i will solve that don't just keep it untouched for a week or so. its a request @subhadipbhowmik 
Fixes #149 
https://github.com/user-attachments/assets/df76c2f0-7e0e-415c-af0b-e9027e4713b8
@subhadipbhowmik Check this PR and merge it and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level. i think it can be level 3 because the page is very important in open source to showcase the efforts of the people contributing in building it and it is not static it is dynamic as a new contributor is added to your repo it will be automatically added there so this is the beauty of this.
=> Added the Contributors Page

site/components/Footer.js
I have changed the name of website in the footer
Fixes #234
=> fix footer bug

site/package-lock.json, site/pages/_app.js, site/styles/globals.css, site/tailwind.config.js
i added the dark mode feature to the website
Fixes #351 
proof
https://github.com/user-attachments/assets/35a26c61-f029-414d-9ede-6bdeb24a0635
- [X ] New feature (non-breaking change which adds functionality)
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] I have commented on my code, particularly in hard-to-understand areas
- [X ] New and existing unit tests pass locally with my changes
=> Add dark mode toggle button

site/components/Navbar.js, site/pages/about.js
About us page helps users to know more about the website and project, learns mission and vission of the project.
Fixes #376 
https://github.com/user-attachments/assets/965a85b4-d0f1-46f6-8ff2-7edbdd84d141
- [X ] New feature (non-breaking change which adds functionality)
- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented on my code, particularly in hard-to-understand areas
- [ X] New and existing unit tests pass locally with my changes
=> Added About Us feature to navigation
